sudo: required
language: d
services:
- docker
script:
# lib{json,uri}-perl is required for `make shellcheck`
- sudo apt-get install libjson-perl liburi-perl
- make shellcheck
- mkdir -pv output/
- curl -fsS https://dlang.org/install.sh | bash -s ldc
- make tests

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/228a31b6140b028bcf79
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
